name: Build macOS

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        path: ladybird
        
    - name: Install build dependencies
      run: |
        # Install LLVM/Clang from Homebrew (minimum clang-19 required)
        brew install llvm@20 autoconf autoconf-archive automake ccache cmake nasm ninja pkg-config qt
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Configure ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: macos-build
        max-size: 2G
        
    - name: Set environment variables
      run: |
        # Use Homebrew clang instead of Xcode clang (minimum clang-19 required, we install clang-20)
        echo "CC=$(brew --prefix llvm@20)/bin/clang" >> $GITHUB_ENV
        echo "CXX=$(brew --prefix llvm@20)/bin/clang++" >> $GITHUB_ENV
        echo "CMAKE_BUILD_PARALLEL_LEVEL=$(sysctl -n hw.ncpu)" >> $GITHUB_ENV
        
    - name: Build Ladybird
      working-directory: ladybird
      run: |
        python3 -m venv build-env
        source build-env/bin/activate
        ./Meta/ladybird.py build
        
    - name: Create application bundle
      if: ${{ github.ref == 'refs/heads/main' }}
      working-directory: ladybird
      run: |
        # Create a distributable app bundle
        mkdir -p ladybird-macos
        cp -R Build/release/bin/Ladybird.app ladybird-macos/
        
        # Create a compressed archive
        tar -czf ladybird-macos.tar.gz -C ladybird-macos Ladybird.app
        
    - name: Upload build artifacts
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/upload-artifact@v4
      with:
        name: ladybird-macos-${{ github.sha }}
        path: ladybird/ladybird-macos.tar.gz
        retention-days: 30
        
    - name: Upload app bundle (uncompressed)
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/upload-artifact@v4
      with:
        name: ladybird-macos-app-${{ github.sha }}
        path: ladybird/Build/release/bin/Ladybird.app
        retention-days: 7