name: Build

on: [push]

jobs:
  
  build:
    
    runs-on: macos-15
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          brew install autoconf autoconf-archive automake ccache cmake nasm ninja pkg-config

      - name: Build
        run: |
          cd ladybird
          Meta/ladybird.sh build
          zip -r Ladybird.zip Build/release/bin/Ladybird.app
          cd -

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ladybird/Ladybird.zip
